from __future__ import annotations

import asyncio
import logging
import os
import shutil
import signal
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import IO

from flow44.sandbox.pty import PtyHandle, _active_ptys

logger = logging.getLogger(__name__)


@dataclass
class SandboxInfo:
    session_id: str
    workspace_dir: str
    port: int


_BASHRC_CONTENT = (
    "# Auto-generated by ai-builder\n"
    'export PS1="\\[\\033[1;35m\\]⚡\\[\\033[0m\\] '
    "\\[\\033[1;34m\\]\\W\\[\\033[0m\\] "
    '\\[\\033[1;36m\\]❯\\[\\033[0m\\] "\n'
    "export CLICOLOR=1\n"
    "export LSCOLORS=GxFxCxDxBxegedabagaced\n"
    "alias ls='ls --color=auto'\n"
    "alias grep='grep --color=auto'\n"
)


def _ensure_bashrc(workspace_dir: str) -> str:
    path = os.path.join(workspace_dir, ".bashrc")
    with open(path, "w", encoding="utf-8") as f:
        f.write(_BASHRC_CONTENT)
    return path


async def _kill_process_tree(proc: asyncio.subprocess.Process) -> None:
    """Kill a process and its entire group (Unix only)."""
    if proc.returncode is not None:
        return
    try:
        pgid = os.getpgid(proc.pid)
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            proc.kill()
        except ProcessLookupError:
            pass
    try:
        await proc.wait()
    except ProcessLookupError:
        pass


class Sandbox(ABC):
    def __init__(self, info: SandboxInfo) -> None:
        self.info = info
        self._dev_process: asyncio.subprocess.Process | None = None
        self._dev_log_file: IO[bytes] | None = None
        self._pty: PtyHandle | None = None

    @property
    def session_id(self) -> str:
        return self.info.session_id

    @property
    def workspace_dir(self) -> str:
        return self.info.workspace_dir

    @property
    def port(self) -> int:
        return self.info.port

    # -- Lifecycle --

    async def start(self) -> None:
        os.makedirs(self.workspace_dir, exist_ok=True)

    async def destroy(self, *, delete_workspace: bool = True) -> None:
        await self.stop_dev_server()
        self.kill_pty()
        if delete_workspace and os.path.isdir(self.workspace_dir):
            shutil.rmtree(self.workspace_dir, ignore_errors=True)

    # -- Command execution --

    @abstractmethod
    def exec(self, command: str) -> AsyncIterator[str]: ...

    # -- Dev server --

    @abstractmethod
    async def start_dev_server(self) -> None: ...

    async def stop_dev_server(self) -> None:
        if self._dev_process is not None:
            await _kill_process_tree(self._dev_process)
            self._dev_process = None
        if self._dev_log_file is not None:
            try:
                self._dev_log_file.close()
            except Exception:
                logger.debug("Failed to close dev log file", exc_info=True)
            self._dev_log_file = None

    def dev_server_running(self) -> bool:
        return self._dev_process is not None and self._dev_process.returncode is None

    # -- PTY --

    @abstractmethod
    def create_pty(self) -> PtyHandle: ...

    def get_or_create_pty(self) -> PtyHandle:
        if self._pty is not None and self._pty.alive():
            return self._pty
        self.kill_pty()
        self._pty = self.create_pty()
        return self._pty

    def kill_pty(self) -> None:
        if self._pty is not None:
            _active_ptys.discard(self._pty)
            self._pty.kill()
            self._pty = None

    # -- File I/O --

    async def read_file(self, path: str) -> str:
        full = self._safe_path(path)
        with open(full, encoding="utf-8") as f:
            return f.read()

    async def write_file(self, path: str, content: str) -> None:
        full = self._safe_path(path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)

    def _safe_path(self, relative_path: str) -> str:
        workspace = os.path.realpath(self.workspace_dir)
        cleaned = relative_path.lstrip("/")
        target = os.path.realpath(os.path.join(workspace, cleaned))
        if not target.startswith(workspace):
            raise PermissionError(f"Path traversal detected: {relative_path}")
        return target
