import asyncio
import logging
import os
import signal
import subprocess
from collections.abc import AsyncIterator

if os.name == "posix":
    import fcntl

from flow44.sandbox.base import BaseSandbox
from flow44.sandbox.pty import UnixPTY

_BASHRC_CONTENT = (
    "# Auto-generated by flow-44-maz\n"
    'export PS1="\\[\\033[1;35m\\]⚡\\[\\033[0m\\] '
    "\\[\\033[1;34m\\]\\W\\[\\033[0m\\] "
    '\\[\\033[1;36m\\]❯\\[\\033[0m\\] "\n'
    "export CLICOLOR=1\n"
    "export LSCOLORS=GxFxCxDxBxegedabagaced\n"
    "alias ls='ls --color=auto'\n"
    "alias grep='grep --color=auto'\n"
)


def _ensure_bashrc(workspace_dir: str) -> str:
    path = os.path.join(workspace_dir, ".bashrc")
    with open(path, "w", encoding="utf-8") as f:
        f.write(_BASHRC_CONTENT)
    return path


logger = logging.getLogger(__name__)


class UnixSandbox(BaseSandbox):
    async def exec(self, command: str) -> AsyncIterator[str]:
        cmd = ["/bin/bash", "-c", f"cd {self.workspace_dir} && {command}"]

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT,
        )

        if proc.stdout is None:
            return
        while True:
            line = await proc.stdout.readline()
            if not line:
                break
            yield line.decode(errors="replace")

        await proc.wait()

    async def _spawn_background(self, name: str, command: str, env: dict[str, str]) -> None:
        log_path = self.get_background_log_path(name)
        log_file = open(log_path, "wb")  # noqa: ASYNC230, SIM115

        proc = await asyncio.create_subprocess_exec(
            "/bin/bash",
            "-c",
            f"cd {self.workspace_dir} && {command}",
            stdin=asyncio.subprocess.DEVNULL,
            stdout=log_file,
            stderr=asyncio.subprocess.STDOUT,
            env=env,
            start_new_session=True,
        )

        self._bg_processes[name] = proc
        self._bg_log_files[name] = log_file
        logger.debug("Background process '%s' started (pid %s)", name, proc.pid)

    @classmethod
    def find_pids_in_port_range(cls, port_start: int, port_end: int) -> list[tuple[int, int]]:
        """Return (pid, port) pairs for processes using ports in range (via lsof).

        TODO: this only catches processes that bound a port. Processes spawned via the
          terminal (e.g. a custom server, a long-running script) are missed. A more complete
          approach would scan by workspace directory: `lsof +D <workspace_dir>` finds all
          processes with open files inside the workspace, or `pgrep -f <workspace_dir>` finds
          processes whose cmdline references it. Consider adding find_pids_in_workspace(workspace_dir)
          as a second cleanup pass in _kill_orphan_processes.
        """
        try:
            result = subprocess.run(  # noqa: PLW1510
                ["lsof", "-i", f"TCP:{port_start}-{port_end}", "-P", "-n", "-F", "pn"],  # noqa: S607
                capture_output=True,
                text=True,
                timeout=5,
            )
            pairs: list[tuple[int, int]] = []
            pid: int | None = None
            for line in result.stdout.splitlines():
                if line.startswith("p"):
                    try:
                        pid = int(line[1:])
                    except ValueError:
                        pid = None
                elif line.startswith("n") and pid is not None:
                    try:
                        port = int(line.rsplit(":", 1)[1])
                        if port_start <= port <= port_end:
                            pairs.append((pid, port))
                    except (ValueError, IndexError):
                        pass
            return pairs
        except FileNotFoundError:
            return []
        except Exception:
            logger.debug("Failed to find pids in port range", exc_info=True)
            return []

    @classmethod
    def kill_pid(cls, pid: int) -> None:
        try:
            os.killpg(os.getpgid(pid), signal.SIGTERM)
        except (ProcessLookupError, PermissionError, OSError):
            try:
                os.kill(pid, signal.SIGTERM)
            except (ProcessLookupError, PermissionError):
                pass

    def create_pty(self) -> UnixPTY:
        master_fd, slave_fd = os.openpty()

        env = os.environ.copy()
        env["TERM"] = "xterm-256color"
        env["CLICOLOR"] = "1"
        env["LSCOLORS"] = "GxFxCxDxBxegedabagaced"
        env["HOME"] = self.workspace_dir

        bashrc_path = _ensure_bashrc(self.workspace_dir)

        pid = os.fork()
        if pid == 0:
            os.close(master_fd)
            os.setsid()
            fcntl.ioctl(slave_fd, __import__("termios").TIOCSCTTY, 0)
            os.dup2(slave_fd, 0)
            os.dup2(slave_fd, 1)
            os.dup2(slave_fd, 2)
            if slave_fd > 2:
                os.close(slave_fd)
            os.chdir(self.workspace_dir)
            os.execvpe("/bin/bash", ["/bin/bash", "--rcfile", bashrc_path], env)  # noqa: S606

        os.close(slave_fd)

        flags = fcntl.fcntl(master_fd, fcntl.F_GETFL)
        fcntl.fcntl(master_fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)

        pty = UnixPTY(read_fd=master_fd, write_fd=master_fd, pid=pid)
        return pty
