apiVersion: v1
kind: Service
metadata:
  name: {{ include "langfuse.fullname" . }}-web
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "langfuse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
