apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "langfuse.fullname" . }}-minio
  labels:
    {{- include "langfuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.minio.size }}
