"""Optimize publishing: repurpose published_url and add published_at

Revision ID: 441ccbed0e31
Revises: 9d6eeadce019
Create Date: 2026-04-20 23:46:07.911704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '441ccbed0e31'
down_revision: Union[str, Sequence[str], None] = '9d6eeadce019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('projects', sa.Column('published_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('projects', 'published_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'projects', ['published_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.alter_column('projects', 'published_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'published_at')
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
