"""add_published_slug_to_project

Revision ID: 218bf93cf485
Revises: 9d6eeadce019
Create Date: 2026-04-16 12:43:56.045113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '218bf93cf485'
down_revision: Union[str, Sequence[str], None] = '9d6eeadce019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('projects', sa.Column('published_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_unique_constraint('uq_projects_published_slug', 'projects', ['published_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_published_slug', 'projects', type_='unique')
    op.drop_column('projects', 'published_slug')
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
