"""add heartbeat table and agent_events created_at and fk

Revision ID: f550c1c17fde
Revises: 9252bbb0fae2
Create Date: 2026-06-25 17:26:14.850158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f550c1c17fde'
down_revision: Union[str, Sequence[str], None] = '9252bbb0fae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_heartbeat',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('beat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.execute("DELETE FROM agent_events WHERE project_id NOT IN (SELECT id FROM projects)")
    op.alter_column('agent_events', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               server_default=sa.func.now(),
               postgresql_using='created_at::timestamptz')
    op.create_foreign_key(
        'agent_events_project_id_fkey', 'agent_events', 'projects', ['project_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_events_project_id_fkey', 'agent_events', type_='foreignkey')
    op.alter_column('agent_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               server_default=None,
               postgresql_using='created_at::text')
    op.drop_table('agent_run_heartbeat')
    # ### end Alembic commands ###
