"""add platform_users and project_members tables

Revision ID: bf979c9b9417
Revises: b86606ea84cc
Create Date: 2026-06-08 10:26:27.824590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf979c9b9417'
down_revision: Union[str, Sequence[str], None] = 'b86606ea84cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('project_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: grant platform access to all existing project owners
    bind = op.get_bind()
    dialect = bind.dialect.name if bind else "postgresql"

    if dialect == "sqlite":
        op.execute(
            """
            INSERT OR IGNORE INTO platform_users (user_id, invited_by, created_at)
            SELECT DISTINCT user_id, 'system', datetime('now')
            FROM projects
            WHERE user_id IS NOT NULL AND user_id != ''
            """
        )
    else:
        op.execute(
            """
            INSERT INTO platform_users (user_id, invited_by, created_at)
            SELECT DISTINCT user_id, 'system', NOW()::text
            FROM projects
            WHERE user_id IS NOT NULL AND user_id != ''
            ON CONFLICT (user_id) DO NOTHING
            """
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_table('platform_users')
    # ### end Alembic commands ###
