"""add published_at and unique published_url handle

Revision ID: b86606ea84cc
Revises: 574c4ddfe002
Create Date: 2026-06-01 19:33:53.414867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b86606ea84cc'
down_revision: Union[str, Sequence[str], None] = '574c4ddfe002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('published_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('projects', 'published_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE projects SET published_url = NULL WHERE published_url = ''")
    op.create_unique_constraint('uq_projects_published_url', 'projects', ['published_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_published_url', 'projects', type_='unique')
    op.execute("UPDATE projects SET published_url = '' WHERE published_url IS NULL")
    op.alter_column('projects', 'published_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('projects', 'published_at')
    # ### end Alembic commands ###
