"""Add user_id to projects

Revision ID: 574c4ddfe002
Revises: 9d6eeadce019
Create Date: 2026-05-04 15:08:56.544564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '574c4ddfe002'
down_revision: Union[str, Sequence[str], None] = '9d6eeadce019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # 1. Add user_id as nullable first
    op.add_column('projects', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # 2. Update existing rows with a default user_id
    op.execute("UPDATE projects SET user_id = 'anonymous' WHERE user_id IS NULL")
    
    # 3. Make it non-nullable and add index
    op.alter_column('projects', 'user_id', nullable=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_column('projects', 'user_id')
    op.alter_column('pending_plans', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
