from __future__ import annotations

import asyncio
import logging
import os
import shutil
import signal
from abc import ABC, abstractmethod
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import IO

from app.sandbox.pty import PtyHandle, _active_ptys

logger = logging.getLogger(__name__)

if os.name != "nt":
    import fcntl  # type: ignore[import-not-found]


@dataclass
class SandboxInfo:
    session_id: str
    workspace_dir: str
    port: int


_BASHRC_CONTENT = (
    "# Auto-generated by ai-builder\n"
    'export PS1="\\[\\033[1;35m\\]⚡\\[\\033[0m\\] '
    '\\[\\033[1;34m\\]\\W\\[\\033[0m\\] '
    '\\[\\033[1;36m\\]❯\\[\\033[0m\\] "\n'
    "export CLICOLOR=1\n"
    "export LSCOLORS=GxFxCxDxBxegedabagaced\n"
    "alias ls='ls --color=auto'\n"
    "alias grep='grep --color=auto'\n"
)


def _ensure_bashrc(workspace_dir: str) -> str:
    path = os.path.join(workspace_dir, ".bashrc")
    with open(path, "w") as f:
        f.write(_BASHRC_CONTENT)
    return path


async def _kill_process_tree(proc: asyncio.subprocess.Process) -> None:
    if proc.returncode is not None:
        return
    try:
        pgid = os.getpgid(proc.pid)
        os.killpg(pgid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            proc.kill()
        except ProcessLookupError:
            pass
    try:
        await proc.wait()
    except ProcessLookupError:
        pass


class Sandbox(ABC):

    def __init__(self, info: SandboxInfo) -> None:
        self.info = info
        self._dev_process: asyncio.subprocess.Process | None = None
        self._dev_log_file: IO[bytes] | None = None
        self._ptys: set[PtyHandle] = set()

    @property
    def session_id(self) -> str:
        return self.info.session_id

    @property
    def workspace_dir(self) -> str:
        return self.info.workspace_dir

    @property
    def port(self) -> int:
        return self.info.port

    # -- Lifecycle --

    async def start(self) -> None:
        os.makedirs(self.workspace_dir, exist_ok=True)

    async def destroy(self, *, delete_workspace: bool = True) -> None:
        await self.stop_dev_server()
        for pty in list(self._ptys):
            self.close_pty(pty)
        if delete_workspace and os.path.isdir(self.workspace_dir):
            shutil.rmtree(self.workspace_dir, ignore_errors=True)

    # -- Command execution --

    @abstractmethod
    def exec(self, command: str) -> AsyncIterator[str]: ...

    # -- Dev server --

    @abstractmethod
    async def _spawn_dev_server(self) -> asyncio.subprocess.Process: ...

    async def start_dev_server(self) -> None:
        if os.name == "nt":
            logger.info("Skipping dev server on Windows (session %s)", self.session_id)
            return

        await self.stop_dev_server()

        log_path = os.path.join(self.workspace_dir, ".dev-server.log")
        self._dev_log_file = open(log_path, "wb")  # noqa: SIM115

        self._dev_process = await self._spawn_dev_server()
        logger.info(
            "Dev server started for session %s on port %d (pid %s)",
            self.session_id, self.port, self._dev_process.pid,
        )

    async def stop_dev_server(self) -> None:
        if self._dev_process is not None:
            await _kill_process_tree(self._dev_process)
            self._dev_process = None
        if self._dev_log_file is not None:
            try:
                self._dev_log_file.close()
            except Exception:
                pass
            self._dev_log_file = None

    def dev_server_running(self) -> bool:
        return self._dev_process is not None and self._dev_process.returncode is None

    # -- PTY --

    @abstractmethod
    def _spawn_pty(self, master_fd: int, slave_fd: int, env: dict[str, str], bashrc_path: str) -> int: ...

    def create_pty(self) -> PtyHandle:
        if os.name == "nt":
            return self._create_winpty()
        return self._create_unix_pty()

    def _create_unix_pty(self) -> PtyHandle:
        master_fd, slave_fd = os.openpty()

        env = os.environ.copy()
        env["TERM"] = "xterm-256color"
        env["CLICOLOR"] = "1"
        env["LSCOLORS"] = "GxFxCxDxBxegedabagaced"

        bashrc_path = _ensure_bashrc(self.workspace_dir)
        pid = self._spawn_pty(master_fd, slave_fd, env, bashrc_path)
        os.close(slave_fd)

        flags = fcntl.fcntl(master_fd, fcntl.F_GETFL)
        fcntl.fcntl(master_fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)

        handle = PtyHandle(read_fd=master_fd, write_fd=master_fd, pid=pid, session_id=self.session_id)
        self._ptys.add(handle)
        _active_ptys.add(handle)
        return handle

    def _create_winpty(self) -> PtyHandle:
        from winpty import PtyProcess as WinPtyProcess  # type: ignore[import-untyped]

        _ensure_bashrc(self.workspace_dir)
        proc = WinPtyProcess.spawn("cmd.exe", cwd=self.workspace_dir)

        handle = PtyHandle(pid=proc.pid, session_id=self.session_id, winpty_process=proc)
        self._ptys.add(handle)
        _active_ptys.add(handle)
        return handle

    def close_pty(self, pty: PtyHandle) -> None:
        self._ptys.discard(pty)
        _active_ptys.discard(pty)
        pty.kill()

    # -- File I/O --

    async def read_file(self, path: str) -> str:
        full = self._safe_path(path)
        with open(full, "r", encoding="utf-8") as f:
            return f.read()

    async def write_file(self, path: str, content: str) -> None:
        full = self._safe_path(path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)

    def _safe_path(self, relative_path: str) -> str:
        workspace = os.path.realpath(self.workspace_dir)
        cleaned = relative_path.lstrip("/")
        target = os.path.realpath(os.path.join(workspace, cleaned))
        if not target.startswith(workspace):
            raise PermissionError(f"Path traversal detected: {relative_path}")
        return target
