"""PTY-backed process for interactive terminal sessions."""

from __future__ import annotations

import atexit
import fcntl
import os
import signal
import subprocess
from dataclasses import dataclass

from app.config import settings
from app.sandbox.manager import sandbox_manager
from app.sandbox.nsjail import _nsjail_available


@dataclass(eq=False)
class PtyProcess:
    """Handle to a PTY-backed shell process."""

    read_fd: int
    write_fd: int
    pid: int
    session_id: str = ""


# Global registry of active PTY processes so we can clean them all up.
_active_ptys: set[PtyProcess] = set()


def create_pty_process(session_id: str) -> PtyProcess:
    """Fork a PTY-backed bash process inside the sandbox workspace.

    On systems without nsjail the shell runs directly in the workspace dir.
    """
    sandbox = sandbox_manager.get_sandbox(session_id)
    workspace_dir = sandbox.workspace_dir if sandbox else os.path.join(settings.WORKSPACE_BASE_DIR, session_id)

    master_fd, slave_fd = os.openpty()

    env = os.environ.copy()
    env["TERM"] = "xterm-256color"
    env["CLICOLOR"] = "1"
    env["LSCOLORS"] = "GxFxCxDxBxegedabagaced"

    # Write a .bashrc with a colorful prompt and aliases
    bashrc_path = os.path.join(workspace_dir, ".bashrc")
    if not os.path.exists(bashrc_path):
        with open(bashrc_path, "w") as f:
            f.write(
                "# Auto-generated by ai-builder\n"
                'export PS1="\\[\\033[1;35m\\]⚡\\[\\033[0m\\] '
                '\\[\\033[1;34m\\]\\W\\[\\033[0m\\] '
                '\\[\\033[1;36m\\]❯\\[\\033[0m\\] "\n'
                "export CLICOLOR=1\n"
                "export LSCOLORS=GxFxCxDxBxegedabagaced\n"
                "alias ls='ls --color=auto 2>/dev/null || ls -G'\n"
                "alias grep='grep --color=auto'\n"
            )

    if _nsjail_available() and sandbox is not None:
        # Inside nsjail the workspace is mounted at /home/project
        env["HOME"] = "/home/project"
        from app.sandbox.nsjail import build_nsjail_command

        cmd = build_nsjail_command(session_id, workspace_dir, sandbox.port, command=None)
        proc = subprocess.Popen(
            cmd,
            stdin=slave_fd,
            stdout=slave_fd,
            stderr=slave_fd,
            preexec_fn=os.setsid,
            env=env,
        )
        pid = proc.pid
    else:
        # macOS / dev fallback — HOME is the real workspace dir
        env["HOME"] = workspace_dir
        pid = os.fork()
        if pid == 0:
            # Child process
            os.close(master_fd)
            os.setsid()
            fcntl.ioctl(slave_fd, __import__("termios").TIOCSCTTY, 0)
            os.dup2(slave_fd, 0)
            os.dup2(slave_fd, 1)
            os.dup2(slave_fd, 2)
            if slave_fd > 2:
                os.close(slave_fd)
            os.chdir(workspace_dir)
            os.execvpe("/bin/bash", ["/bin/bash", "--rcfile", bashrc_path], env)

    os.close(slave_fd)

    # Set master_fd to non-blocking for async reads
    flags = fcntl.fcntl(master_fd, fcntl.F_GETFL)
    fcntl.fcntl(master_fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)

    pty_proc = PtyProcess(read_fd=master_fd, write_fd=master_fd, pid=pid, session_id=session_id)
    _active_ptys.add(pty_proc)
    return pty_proc


def read_pty(pty_proc: PtyProcess) -> bytes:
    """Non-blocking read from the PTY master fd."""
    try:
        return os.read(pty_proc.read_fd, 4096)
    except BlockingIOError:
        return b""
    except OSError:
        return b""


def write_pty(pty_proc: PtyProcess, data: bytes) -> None:
    """Write raw bytes (keystrokes) to the PTY."""
    os.write(pty_proc.write_fd, data)


def close_pty(pty_proc: PtyProcess) -> None:
    """Close the PTY and kill the entire process group (bash + pnpm + node etc.)."""
    _active_ptys.discard(pty_proc)

    try:
        os.close(pty_proc.read_fd)
    except OSError:
        pass

    # Kill the entire process group so child processes (pnpm, node, esbuild)
    # don't survive as zombies.  os.setsid() in the fork made the PTY shell
    # the leader of its own process group, so killpg reaches all descendants.
    try:
        os.killpg(os.getpgid(pty_proc.pid), signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        # Fallback: kill just the PID
        try:
            os.kill(pty_proc.pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            pass

    # Reap the zombie so it doesn't linger in the process table
    try:
        os.waitpid(pty_proc.pid, os.WNOHANG)
    except ChildProcessError:
        pass


def cleanup_session_ptys(session_id: str) -> None:
    """Kill all PTY processes belonging to a specific session."""
    for pty_proc in list(_active_ptys):
        if pty_proc.session_id == session_id:
            close_pty(pty_proc)


def cleanup_all_ptys() -> None:
    """Kill every active PTY process. Called on server shutdown."""
    for pty_proc in list(_active_ptys):
        close_pty(pty_proc)


# Best-effort cleanup when the Python process exits (Ctrl+C, kill, etc.)
atexit.register(cleanup_all_ptys)
