name: uv setup

inputs:
  working-directory:
    required: false
    description: "directory to run uv sync"
    default: "."

description: |
  This action installs python and uv and then installs dependencies from a uv.lock file.

runs:
  using: "composite"
  steps:
    - name: setup python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        prune-cache: false
        cache-dependency-glob: |
          cache.txt

    - name: install python packages
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        uv python pin ${{ env.PYTHON_VERSION }}
        uv sync
        
