name: Update Research Package Version on Push to Branch

on:
  push:
    secrets:
      ACTIONS_APP_SECRET:
        description: 'Action app secret'
        required: true
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

jobs:
  call-update-package:
    uses: ./.github/workflows/bump-package-version.yaml
    secrets: inherit
    if: github.actor != 'primesec-actions[bot]'
    with:
      bump_version_type: 'alpha'
