name: Package CI/CD Pipeline

on:
  # Note: this does not trigger when a PR has merge conflict.
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION }}

jobs:
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: setup python and uv
        uses: ./.github/actions/uv-setup

      - name: ruff
        shell: bash
        run: uv run task ruff-dry-all

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: setup python and uv
        uses: ./.github/actions/uv-setup

      - name: mypy
        shell: bash
        run: uv run task mypy-all

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: setup python and uv
        uses: ./.github/actions/uv-setup

      - name: Run tests for pull requests
        shell: bash
        run: uv run task tests

  package-scan:
    name: Package Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: setup python and uv
        uses: ./.github/actions/uv-setup

      - name: Build package
        shell: bash
        run: uv build

      - name: Scan package dependencies
        uses: anchore/scan-action@v6.2.0
        with:
          severity-cutoff: high
          only-fixed: true
          output-format: table