"""Optional package registry and helpers for generated apps."""

from flow44.ai.agents.optional_packages.registry import (
    OPTIONAL_PACKAGES,
    OptionalPackage,
    OptionalPackageDecision,
    OptionalPackagePrompt,
    SelectedOptionalPackage,
    allowed_import_names,
    has_capability,
    high_confidence_optional_package_decision,
    merge_optional_package_decisions,
    optional_packages_prompt_context,
    package_capabilities,
    package_install_names,
    render_optional_package_prompts,
    repair_unselected_package_references,
    selected_package_names,
    selected_packages_from_package_json,
    validate_optional_package_decision,
    validate_optional_packages,
)

__all__ = [
    "OPTIONAL_PACKAGES",
    "OptionalPackage",
    "OptionalPackageDecision",
    "OptionalPackagePrompt",
    "SelectedOptionalPackage",
    "allowed_import_names",
    "has_capability",
    "high_confidence_optional_package_decision",
    "merge_optional_package_decisions",
    "optional_packages_prompt_context",
    "package_capabilities",
    "package_install_names",
    "render_optional_package_prompts",
    "repair_unselected_package_references",
    "selected_package_names",
    "selected_packages_from_package_json",
    "validate_optional_package_decision",
    "validate_optional_packages",
]
